################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
OBJCOPY_HEX := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Src/ui/components \
Core/Src/ui/screens \
Core/Src/ui \
Core/Startup \
Display_Driver/lvgl/env_support/pikascript \
Display_Driver/lvgl/env_support/rt-thread \
Display_Driver/lvgl/env_support/rt-thread/squareline \
Display_Driver/lvgl/src/core \
Display_Driver/lvgl/src/display \
Display_Driver/lvgl/src/draw/convert/helium \
Display_Driver/lvgl/src/draw/convert \
Display_Driver/lvgl/src/draw/convert/neon \
Display_Driver/lvgl/src/draw/dma2d \
Display_Driver/lvgl/src/draw/espressif/ppa \
Display_Driver/lvgl/src/draw/eve \
Display_Driver/lvgl/src/draw \
Display_Driver/lvgl/src/draw/nema_gfx \
Display_Driver/lvgl/src/draw/nxp/g2d \
Display_Driver/lvgl/src/draw/nxp/pxp \
Display_Driver/lvgl/src/draw/opengles \
Display_Driver/lvgl/src/draw/renesas/dave2d \
Display_Driver/lvgl/src/draw/sdl \
Display_Driver/lvgl/src/draw/sw/blend/helium \
Display_Driver/lvgl/src/draw/sw/blend \
Display_Driver/lvgl/src/draw/sw/blend/neon \
Display_Driver/lvgl/src/draw/sw \
Display_Driver/lvgl/src/draw/vg_lite \
Display_Driver/lvgl/src/drivers/display/drm \
Display_Driver/lvgl/src/drivers/display/fb \
Display_Driver/lvgl/src/drivers/display/ft81x \
Display_Driver/lvgl/src/drivers/display/ili9341 \
Display_Driver/lvgl/src/drivers/display/lcd \
Display_Driver/lvgl/src/drivers/display/nv3007 \
Display_Driver/lvgl/src/drivers/display/nxp_elcdif \
Display_Driver/lvgl/src/drivers/display/renesas_glcdc \
Display_Driver/lvgl/src/drivers/display/st7735 \
Display_Driver/lvgl/src/drivers/display/st7789 \
Display_Driver/lvgl/src/drivers/display/st7796 \
Display_Driver/lvgl/src/drivers/display/st_ltdc \
Display_Driver/lvgl/src/drivers/draw/eve \
Display_Driver/lvgl/src/drivers/evdev \
Display_Driver/lvgl/src/drivers/libinput \
Display_Driver/lvgl/src/drivers/nuttx \
Display_Driver/lvgl/src/drivers/opengles/assets \
Display_Driver/lvgl/src/drivers/opengles/glad/src \
Display_Driver/lvgl/src/drivers/opengles \
Display_Driver/lvgl/src/drivers/opengles/opengl_shader \
Display_Driver/lvgl/src/drivers/qnx \
Display_Driver/lvgl/src/drivers/sdl \
Display_Driver/lvgl/src/drivers/uefi \
Display_Driver/lvgl/src/drivers/wayland \
Display_Driver/lvgl/src/drivers/windows \
Display_Driver/lvgl/src/drivers/x11 \
Display_Driver/lvgl/src/font \
Display_Driver/lvgl/src/indev \
Display_Driver/lvgl/src/layouts/flex \
Display_Driver/lvgl/src/layouts/grid \
Display_Driver/lvgl/src/layouts \
Display_Driver/lvgl/src/libs/FT800-FT813 \
Display_Driver/lvgl/src/libs/barcode \
Display_Driver/lvgl/src/libs/bin_decoder \
Display_Driver/lvgl/src/libs/bmp \
Display_Driver/lvgl/src/libs/expat \
Display_Driver/lvgl/src/libs/ffmpeg \
Display_Driver/lvgl/src/libs/freetype \
Display_Driver/lvgl/src/libs/frogfs/src \
Display_Driver/lvgl/src/libs/fsdrv \
Display_Driver/lvgl/src/libs/gif/AnimatedGIF/src \
Display_Driver/lvgl/src/libs/gif \
Display_Driver/lvgl/src/libs/gltf/gltf_view/assets \
Display_Driver/lvgl/src/libs/gltf/gltf_view/ibl \
Display_Driver/lvgl/src/libs/gstreamer \
Display_Driver/lvgl/src/libs/libjpeg_turbo \
Display_Driver/lvgl/src/libs/libpng \
Display_Driver/lvgl/src/libs/lodepng \
Display_Driver/lvgl/src/libs/lz4 \
Display_Driver/lvgl/src/libs/qrcode \
Display_Driver/lvgl/src/libs/rle \
Display_Driver/lvgl/src/libs/rlottie \
Display_Driver/lvgl/src/libs/svg \
Display_Driver/lvgl/src/libs/tiny_ttf \
Display_Driver/lvgl/src/libs/tjpgd \
Display_Driver/lvgl/src/libs/vg_lite_driver/VGLite \
Display_Driver/lvgl/src/libs/vg_lite_driver/VGLiteKernel \
Display_Driver/lvgl/src/libs/vg_lite_driver/lv_vg_lite_hal \
Display_Driver/lvgl/src \
Display_Driver/lvgl/src/misc/cache/class \
Display_Driver/lvgl/src/misc/cache/instance \
Display_Driver/lvgl/src/misc/cache \
Display_Driver/lvgl/src/misc \
Display_Driver/lvgl/src/osal \
Display_Driver/lvgl/src/others/file_explorer \
Display_Driver/lvgl/src/others/font_manager \
Display_Driver/lvgl/src/others/fragment \
Display_Driver/lvgl/src/others/gridnav \
Display_Driver/lvgl/src/others/ime \
Display_Driver/lvgl/src/others/imgfont \
Display_Driver/lvgl/src/others/monkey \
Display_Driver/lvgl/src/others/observer \
Display_Driver/lvgl/src/others/snapshot \
Display_Driver/lvgl/src/others/sysmon \
Display_Driver/lvgl/src/others/test \
Display_Driver/lvgl/src/others/translation \
Display_Driver/lvgl/src/others/vg_lite_tvg \
Display_Driver/lvgl/src/others/xml \
Display_Driver/lvgl/src/others/xml/parsers \
Display_Driver/lvgl/src/stdlib/builtin \
Display_Driver/lvgl/src/stdlib/clib \
Display_Driver/lvgl/src/stdlib \
Display_Driver/lvgl/src/stdlib/micropython \
Display_Driver/lvgl/src/stdlib/rtthread \
Display_Driver/lvgl/src/stdlib/uefi \
Display_Driver/lvgl/src/themes/default \
Display_Driver/lvgl/src/themes \
Display_Driver/lvgl/src/themes/mono \
Display_Driver/lvgl/src/themes/simple \
Display_Driver/lvgl/src/tick \
Display_Driver/lvgl/src/widgets/3dtexture \
Display_Driver/lvgl/src/widgets/animimage \
Display_Driver/lvgl/src/widgets/arc \
Display_Driver/lvgl/src/widgets/arclabel \
Display_Driver/lvgl/src/widgets/bar \
Display_Driver/lvgl/src/widgets/button \
Display_Driver/lvgl/src/widgets/buttonmatrix \
Display_Driver/lvgl/src/widgets/calendar \
Display_Driver/lvgl/src/widgets/canvas \
Display_Driver/lvgl/src/widgets/chart \
Display_Driver/lvgl/src/widgets/checkbox \
Display_Driver/lvgl/src/widgets/dropdown \
Display_Driver/lvgl/src/widgets/image \
Display_Driver/lvgl/src/widgets/imagebutton \
Display_Driver/lvgl/src/widgets/keyboard \
Display_Driver/lvgl/src/widgets/label \
Display_Driver/lvgl/src/widgets/led \
Display_Driver/lvgl/src/widgets/line \
Display_Driver/lvgl/src/widgets/list \
Display_Driver/lvgl/src/widgets/lottie \
Display_Driver/lvgl/src/widgets/menu \
Display_Driver/lvgl/src/widgets/msgbox \
Display_Driver/lvgl/src/widgets/objx_templ \
Display_Driver/lvgl/src/widgets/property \
Display_Driver/lvgl/src/widgets/roller \
Display_Driver/lvgl/src/widgets/scale \
Display_Driver/lvgl/src/widgets/slider \
Display_Driver/lvgl/src/widgets/span \
Display_Driver/lvgl/src/widgets/spinbox \
Display_Driver/lvgl/src/widgets/spinner \
Display_Driver/lvgl/src/widgets/switch \
Display_Driver/lvgl/src/widgets/table \
Display_Driver/lvgl/src/widgets/tabview \
Display_Driver/lvgl/src/widgets/textarea \
Display_Driver/lvgl/src/widgets/tileview \
Display_Driver/lvgl/src/widgets/win \
Drivers/STM32F4xx_HAL_Driver/Src \
Drivers/Touch \
icode/buzzer \
icode/delay \
icode/key \
icode/lcd \
icode/led \
icode/lm75a \
icode/oled \
icode/relay \

