// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: STM32_gui_ros

#include "ui.h"

void action_open_device_list(lv_event_t * e)
{
	// Your code here
}
