// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: STM32_gui_ros

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ButtonScan = NULL;
lv_obj_t * ui_DropdownSTM32 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_ButtonScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        action_open_device_list(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, 282);
    lv_obj_set_height(ui_TextArea1, 277);
    lv_obj_set_x(ui_TextArea1, 205);
    lv_obj_set_y(ui_TextArea1, -39);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 123);
    lv_obj_set_y(ui_Label1, -205);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Information");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonScan = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonScan, 168);
    lv_obj_set_height(ui_ButtonScan, 50);
    lv_obj_set_x(ui_ButtonScan, -274);
    lv_obj_set_y(ui_ButtonScan, -151);
    lv_obj_set_align(ui_ButtonScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DropdownSTM32 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_options(ui_DropdownSTM32, "Option 1\nOption 2\nOption 3");
    lv_obj_set_width(ui_DropdownSTM32, 150);
    lv_obj_set_height(ui_DropdownSTM32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownSTM32, -78);
    lv_obj_set_y(ui_DropdownSTM32, -150);
    lv_obj_set_align(ui_DropdownSTM32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownSTM32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -276);
    lv_obj_set_y(ui_Label2, -149);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Device Scan");

    lv_obj_add_event_cb(ui_ButtonScan, ui_event_ButtonScan, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TextArea1 = NULL;
    ui_Label1 = NULL;
    ui_ButtonScan = NULL;
    ui_DropdownSTM32 = NULL;
    ui_Label2 = NULL;

}
