// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: stm32_gui_ros

#include "ui.h"

void ui_comp_Button1_create_hook(lv_obj_t * comp)
{
}
