// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: simple_button

#include "ui.h"

void calculate(lv_event_t * e)
{
	// 1. Get the TEXT from the Text Areas
	    const char * text1 = lv_textarea_get_text(ui_TextArea2);
	    const char * text2 = lv_textarea_get_text(ui_TextArea3);

	    // 2. Convert Text to Integer (atoi)
	    // If text is empty "", atoi returns 0, which is safe
	    int value1 = atoi(text1);
	    int value2 = atoi(text2);

	    // 3. Calculate
	    int result = value1 + value2;

	    // 4. Display Result
	    lv_label_set_text_fmt(ui_LabelResult, "Result: %d", result);

	    // Optional: Hide keyboard after calculation
	    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);
}
